---
# Deploy the common Hadoop and HDFS config files thru the entire Hadoop infraestructure
# Target hosts: namenode, datanode
# Vars: N/A
#

- name: Deploy the common Hadoop and HDFS config files for every node
  become: true
  become_user: hadoop
  when: inventory_hostname != 'localhost'
  block:
  - name: Configure common core-site.xml file
    blockinfile:
      path: /home/hadoop/{{ version }}/etc/hadoop/core-site.xml
      insertbefore: '</configuration>'
      marker: <!-- {mark} COMMON MAIN HADOOP BLOCK -->
      block: |
        <property>
            <name>fs.defaultFS</name>
            <value>hdfs://{{ groups.namenode | first }}:9000</value>
        </property>
        <property>
            <name>io.file.buffer.size</name>
            <value>131072</value>
        </property>

  - name: Configure hdfs-site.xml file parameters for namenode
    blockinfile:
      path: /home/hadoop/{{ version }}/etc/hadoop/hdfs-site.xml
      insertbefore: '</configuration>'
      marker: <!-- {mark} NN HDFS BLOCK -->
      block: |
        <property>
            <name>dfs.replication</name>
            <value>{{ 1 if ( groups.datanode | length < 3 ) else 3 ) | int }}</value>
        </property>
        <property>
            <name>dfs.blocksize</name>
            <value>65536</value>
        </property>
        <property>
            <name>dfs.namenode.handler.count</name>
            <value>100</value>
        </property>
        <property>
            <name>dfs.namenode.name.dir</name>
            <value>file:/home/hadoop/hdfs/namenode</value>
        </property>

  - name: Configure hdfs-site.xml file parameter for datanodes
    blockinfile:
      path: /home/hadoop/{{ version }}/etc/hadoop/hdfs-site.xml
      insertbefore: '</configuration>'
      marker: <!-- {mark} DN HDFS BLOCK -->
      block: |
        <property>
            <name>dfs.datanode.name.dir</name>
            <value>file:/home/hadoop/hdfs/datanode</value>
        </property>

...
