---
# Deploy the YARN config file thru the entire Hadoop infraestructure
# Target hosts: namenode, datanode
# Vars: N/A
#

- name: Deploy the YARN config file for every node
  become: true
  become_user: "{{ username }}"
  when: inventory_hostname != 'localhost'
  block:
  - name: Configure yarn-site.xml file common parameters for ResourceManager and NodeManager
    blockinfile:
      path: "/home/{{ username }}/{{ version }}/etc/hadoop/yarn-site.xml"
      insertbefore: '</configuration>'
      marker: <!-- {mark} COMMON RM AND NM BLOCK -->
      block: |
        <property>
            <name>yarn.acl.enable</name>
            <value>false</value>
        </property>
        <property>
            <name>yarn.log-aggregation-enable</name>
            <value>false</value>
        </property>

  - name: Configure yarn-site.xml file parameters for ResourceManager
    blockinfile:
      path: "/home/{{ username }}/{{ version }}/etc/hadoop/yarn-site.xml"
      insertbefore: '</configuration>'
      marker: <!-- {mark} RM BLOCK -->
      block: |
        <property>
            <name>yarn.resourcemanager.address</name>
            <value>{{ groups.namenode | first }}:8050</value>
        </property>
        <property>
            <name>yarn.resourcemanager.scheduler.address</name>
            <value>{{ groups.namenode | first }}:8035</value>
        </property>
        <property>
            <name>yarn.resourcemanager.resource-tracker.address</name>
            <value>{{ groups.namenode | first }}:8025</value>
        </property>
        <property>
            <name>yarn.scheduler.minimum-allocation-mb</name>
            <value>128</value>
        </property>
        <property>
            <name>yarn.scheduler.maximum-allocation-mb</name>
            <value>{{ ( ansible_memtotal_mb * 3 / 4 ) | int }}</value>
        </property>

  - name: Configure yarn-site.xml file parameters for NodeManager
    blockinfile:
      path: "/home/{{ username }}/{{ version }}/etc/hadoop/yarn-site.xml"
      insertbefore: '</configuration>'
      marker: <!-- {mark} NM BLOCK -->
      block: |
        <property>
            <name>yarn.nodemanager.resource.memory-mb</name>
            <value>{{ ( ansible_memtotal_mb * 3 / 4 ) | int }}</value>
        </property>
        <property>
            <name>yarn.nodemanager.vmem-pmem-ratio</name>
            <value>2.1</value>
        </property>
        <property>
            <name>yarn.nodemanager.vmem-check-enabled</name>
            <value>false</value>
        </property>
        <property>
            <name>yarn.nodemanager.aux-services</name>
            <value>mapreduce_shuffle</value>
        </property>
        <property>
            <name>yarn.nodemanager.aux-services.mapreduce_shuffle.class</name>
            <value>org.apache.hadoop.mapred.ShuffleHandler</value>
        </property>

...
