---
# Common_role variables

username: hadoop

username_SHA512_pass: hadoop

packages:
  - regex_name: java-1.8.0-openjdk*

hadoop_version: hadoop-2.10.1

# Cluster ID

clusterid: CID-e0326a94-8ac6-489a-a58e-cfdcc6d39f01

...
