---
# Common_role variables

username: hadoop

username_SHA512_pass: $6$d..u4EGUjXs6wnyI$E8AplKrVBXIEOEinRU.vUDVWY95Duh5vtXZ8i5cr4iHMQB.zljPdFaz09oxssXASIq0V/j/XS1O2DjmytW6os1

packages:
  - regex_name: java-1.8.0-openjdk-devel

version: hadoop-2.10.2

file: hadoop-2.10.2.tar.gz

# Cluster ID

clusterid: CID-e0326a94-8ac6-489a-a58e-cfdcc6d39f01

...
