---
# Main playbook to deploy all the Ansible TFM infraestructure.

- hosts: local:worker:dhcp
  gather_facts: false
  roles:
    - role: ulliaas

- hosts: worker
  gather_facts: false
  roles:
    - role: base

- hosts: namenode:datanode:local
  gather_facts: false
  roles:
    - role: hadoop
#  tasks:
#    - name: Remove hadoop user environment
#      become: true
#      ignore_errors: true
#      when: inventory_hostname != 'localhost'
#      shell: |
#        ps -fuhadoop | grep hadoop | awk '{print $2}' | xargs kill -9
#        rm -rf /var/log/hadoop
#        userdel hadoop
#        rm -rf /home/hadoop

- hosts: tdm_master:tdm_worker:local
  gather_facts: false
  roles:
   - role: spark
#  tasks:
#    - name: Remove spark user environment
#      become: true
#      ignore_errors: true
#      when: inventory_hostname != 'localhost'
#      shell: |
#        ps -fuspark | grep spark | awk '{print $2}' | xargs kill -9
#        rm -rf /var/log/spark
#        userdel spark
#        rm -rf /home/spark

#- hosts: tdm_master:local
#  gather_facts: false
#  roles:
#    - role: kafka
#  tasks:
#    - name: Remove Kafka user environment
#      become: true
#      ignore_errors: true
#      when: inventory_hostname != 'localhost'
#      shell: |
#        ps -fukafka | grep kafka | awk '{print $2}' | xargs kill -9
#        rm -rf /var/log/kafka
#        userdel kafka
#        rm -rf /home/kafka

...
