---
# Main playbook to deploy all the Ansible-Hadoop and TDM infraestructure.
#

- hosts: local:dhcp:worker
  gather_facts: false
  roles:
    - role: ulliaas

#- hosts: worker
#  gather_facts: false
#  roles:
#    - role: base
#
#- hosts: namenode:datanode:local
#  gather_facts: true
#  roles:
#    - role: hadoop
#
#- hosts: tdm_master:tdm_worker:local
#  gather_facts: true
#  roles:
#   - role: spark
#  tasks:
#    - name: Remove spark user environment
#      shell: |
#        ps -fuspark | grep spark | awk '{print $2}' | xargs kill -9
#        rm -rf /home/spark
#        userdel spark
#      become: true
#      when: ( group_names | select('match', 'local') | list | length ) == 0
#      ignore_errors: true
#
#- hosts: tdm_master:local
#  gather_facts: false
#  roles:
#    - role: kafka
#  tasks:
#    - name: Remove Kafka user environment
#      shell: |
#        ps -fukafka | grep kafka | awk '{print $2}' | xargs kill -9
#        rm -rf /home/kafka
#        userdel kafka
#      become: true
#      when: ( group_names | select('match', 'local') | list | length ) == 0
#      ignore_errors: true

...
