---
# Main playbook to deploy all the Ansible TFM infraestructure.

- hosts:
    - local
    - worker
    - dhcp
  gather_facts: false
  roles:
    - role: ulliaas

- hosts: worker
  gather_facts: false
  roles:
    - role: base

- hosts:
    - local
    - namenode
    - datanode
  gather_facts: false
  roles:
    - role: hadoop
#  tasks:
#    - name: Remove hadoop user environment
#      become: true
#      ignore_errors: true
#      when: inventory_hostname != 'localhost'
#      shell: |
#        ps -fuhadoop | grep hadoop | awk '{print $2}' | xargs kill -9
#        rm -rf /var/log/hadoop
#        userdel -r hadoop
#        rm -rf /home/hadoop

- hosts:
    - local
    - tdm_master
    - tdm_worker
  gather_facts: false
  roles:
   - role: spark
#  tasks:
#    - name: Remove spark user environment
#      become: true
#      ignore_errors: true
#      when: inventory_hostname != 'localhost'
#      shell: |
#        ps -fuspark | grep spark | awk '{print $2}' | xargs kill -9
#        rm -rf /var/log/spark
#        userdel -r spark
#        rm -rf /home/spark

#- hosts:
#    - local
#    - tdm_master
#  gather_facts: false
#  roles:
#    - role: kafka
#  tasks:
#    - name: Remove Kafka user environment
#      become: true
#      ignore_errors: true
#      when: inventory_hostname != 'localhost'
#      shell: |
#        ps -fukafka | grep kafka | awk '{print $2}' | xargs kill -9
#        rm -rf /var/log/kafka
#        userdel -r kafka
#        rm -rf /home/kafka

...
