---
# Yum tasks (to be included into other role plays).
# Target hosts: N/A
# Vars: every RPM needed by the parent role
#

- name: Fix 6704151 RedHat8/Centos8 issue with repos
  block:
  - name: Locate all the repo files
    find:
      paths: /etc/yum.repos.d/
      patterns: '*.repo'
    register: repos

  - name: Comment mirrolist line
    replace:
      path: "{{ item.path }}"
      regexp: '^mirrorlist'
      replace: '#mirrorlist'
    with_items: "{{ repos.files }}"

  - name: Uncomment baseurl line
    replace:
      path: "{{ item.path }}"
      regexp: '^#baseurl=http:\/\/mirrorlist'
      replace: 'baseurl=http://vault'
    with_items: "{{ repos.files }}"

  - name: Yum clean all
    command: dnf clean all

  - name: Yum substitute Centos-Linux by Centos-Stream repos
    command: dnf -f swap centos-linux-repos centos-stream-repos

  become: true

- name: Update all OS packages
  yum:
    name: '*'
    state: latest

- name: Install per parent role additional packages
  yum:
    name: "{{ item.regex_name }}"
    state: latest
  with_items: "{{ packages_list }}"

- name: Yum autoremove
  yum:
    autoremove: yes

- name: Yum clean all
  command: yum clean all
  become: true

- name: Update mlocate DB (register all the files into the VM)
  command: updatedb
  become: true

...
