---
# Dnf tasks (to be included into other role plays).
# Target hosts: N/A
# Vars: every RPM needed by the parent role
#

- name: Execute all the Dnf actions
  become: true
  block:
  - name: Update all OS packages
    dnf:
      name: '*'
      state: latest

  - name: Install per parent role additional packages
    dnf:
      name: "{{ item.regex_name }}"
      state: latest
    with_items: "{{ packs }}"

  - name: Dnf autoremove
    dnf:
      autoremove: yes

  - name: Dnf clean all
    command: dnf clean all
    ignore_errors: yes

  - name: Update mlocate DB (register all the files into the VM)
    command: updatedb

...
