---
# Common_role variables

username: spark

username_SHA512_pass: $6$1ReAgM8ZUMgJBvFo$2Iu8Z4dzW0DmSm4zQeLyUHRLtuHLZ5LVmJWNTOFgwUIW.ZJtQj5KaxkaF8Kkqss.zhOCFlwfiYR7FsJ6LKrU4/

packages:
  - regex_name: ncdu
  - regex_name: python38
  - regex_name: scala

version_suburi: spark

version: spark-3.3.0

file: spark-3.3.0-bin-hadoop3.tgz

...
