---
# Deploy the role common infraestructure on every cluster node.
# This is the common base of every technology framework.
# Target hosts: N/A
# Vars: username
#

- name: Check availability of VM's
  copy:
    content: "  VM gestionada por los roles/playbooks de Ansible.\n"
    dest: /etc/motd
  become: true

- name: Include the YUM update role
  include_role:
    name: packages
  vars:
    packs: "{{ packages }}"

- name: Include the technology own user creation role
  include_role:
    name: user_creation
  vars:
    username: "{{ username }}"

- name: Include the technology latest tarball deployment role
  include_role:
    name: tarball_deploy
  vars:
    tarball: "{{ username }}"

...

