---
# Apply the specific filter to get the Spark tarball files list
# Target: localhost

- name: Discard non needed tarballs
  replace:
    path: "{{ role_path }}/files/content"
    regexp: "^[0-9a-zA-Z_\\.]*$"

- name: Discard other needed tarballs
  replace:
    path: "{{ role_path }}/files/content"
    regexp: "^[0-9a-zA-Z\\.]*{{ username }}\\-[0-9a-zA-Z\\.]*$"

- name: Discard more non needed tarballs
  replace:
    path: "{{ role_path }}/files/content"
    regexp: "^{{ username }}\\-[0-9a-zA-Z\\.]*\\-bin\\-[0-9a-zA-Z\\.]*\\-[0-9a-zA-Z\\.]*$"

...
