---
# Initial tasks for every VM deployed.
# Target hosts: worker
#

- name: Generate ansible user SSH keys
  user:
    name: ansible
    generate_ssh_key: yes

- name: Granting read permission to every user for ansible authorized_keys file
  file:
    path: "{{ item }}"
    state: touch
    mode: '0644'
  with_items:
    - /home/ansible/.ssh/id_rsa.pub
    - /home/ansible/.ssh/authorized_keys

- name: Enabling ServerAliveInterval and ServerAliveCountMax in SSH service as client
  become: true
  block:
  - name: Enable Host parameter
    lineinfile:
      path: /etc/ssh/ssh_config
      regexp: '^# Host'
      line: Host

  - name: Enable ServerAlive parameters
    lineinfile:
      path: /etc/ssh/ssh_config
      insertafter: '^Host *'
      line: "{{ item }}"
    with_items:  
      - '  ServerAliveInterval 20'
      - '  ServerAliveCountMax 360'

- name: Enabling ClientAliveInterval and ClientAliveCountMax in SSH service as server
  become: true
  block:
  - name: Enable ClientAlive parameters
    lineinfile:
      path: /etc/ssh/sshd_config
      insertafter: '^UsePAM yes'
      line: "{{ item }}"
    with_items:
      - 'ClientAliveInterval 20'
      - 'ClientAliveCountMax 360'

  - name: Restart SSH service
    service:
      name: sshd
      state: restarted

- name: Disable IPv6 with sysctl
  become: true
  sysctl: name={{ item }} value=1 state=present reload=yes
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: Disable firewalld service
  become: true
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Check availability of VM's
  become: true
  copy:
    content: "  VM gestionada por los roles/playbooks de Ansible.\n"
    dest: /etc/motd

- name: Fix 6704151 RedHat8/Centos8 issue with repos
  become: true
  block:
  - name: Locate all the repo files
    find:
      paths: /etc/yum.repos.d/
      patterns: '*.repo'
    register: repos

  - name: Comment mirrorlist line
    replace:
      path: "{{ item.path }}"
      regexp: '^mirrorlist'
      replace: '#mirrorlist'
    with_items: "{{ repos.files }}"

  - name: Uncomment baseurl line
    replace:
      path: "{{ item.path }}"
      regexp: '^#baseurl=http:\/\/mirro(r|rlist)'
      replace: 'baseurl=http://vault'
    with_items: "{{ repos.files }}"

  - name: Dnf clean all
    command: dnf clean all
    ignore_errors: yes

  - name: Dnf substitute Centos-Linux by Centos-Stream repos
    command: dnf -y swap centos-linux-repos centos-stream-repos
    ignore_errors: yes

- name: Include the DNF update role
  include_tasks: "{{ playbook_dir }}/common_tasks/packages.yml"
  vars:
    packages:
      - regex_name: bind
      - regex_name: bind-utils
      - regex_name: bind-lib*
      - regex_name: binutils
      - regex_name: epel-release
      - regex_name: ksh
      - regex_name: mlocate
      - regex_name: rsync
      - regex_name: tar
      - regex_name: traceroute
      - regex_name: tree
      - regex_name: vim
      - regex_name: wget

- name: Deploying the Java profile.d shell script
  become: true
  block:
  - name: Create an empty Java profile.d file
    file:
      path: /etc/profile.d/java.sh
      owner: root
      group: root
      mode: '0644'
      state: touch

  - name: Fill the Java profile.d file
    copy:
      dest: /etc/profile.d/java.sh
      content: |
        export JAVA_HOME=/etc/alternatives/jre
        export PATH=${JAVA_HOME}/bin:${PATH}

- name: Disable SElinux and reboot workers
  become: true
  block:
  - name: Disable SElinux
    selinux:
      state: disabled
    register: reboot_required

  - name: Reboot the VM
    reboot:
    when: reboot_required.reboot_required

...
