---
# Get the VM IP's from worker nodes
# Target hosts: worker

- name: Get facts
  setup:
    gather_subset: network

- name: Show variable
  debug:
    var: ansible_facts.ens4.ipv4.address

- name: Save the IP facts into remote temp files
  copy:
    content: "  - {{ ansible_facts.ens4.ipv4.address }}"
    dest: '/home/ansible/ip.workers.tmp'

- name: Collect the remote temp files
  register: vm_ip
  slurp:
    src: '/home/ansible/ip.workers.tmp'

- name: Get ips to local var file
  with_items: "{{ vm_ip.content | b64decode }}"
  delegate_to: localhost
  lineinfile:
    path: "{{ role_path }}/vars/vm_ips.yml"
    insertafter: '^vm_ips:$'
    line: "{{ item }}"

...
