---
# Get the VM IP's from worker nodes
# Target hosts: worker

- name: Get the VM network facts
  setup:
    gather_subset: network
  register: netvalues

- name: Show variable
  debug:
    var: netvalues

- name: Register the VM IP
  debug:
    var: netvalues['ens4']['ipv4']['address']
  register: netvars

...
