---
# Deploy the VM either in management or workers subnet, to be a master or a worker node.
# The Router, the DHCP-DNS and the Master server VM's must exists prior to launch this playbook.
# Target hosts: local, workers, dhcp

- name: Login into ULL IaaS
  when: inventory_hostname in groups['local']
  include_tasks: login.yml

- name: Include nodes vars files
  loop:
    - creation.yml
    - removal.yml
  include_vars:
    file: "{{ role_path }}/vars/{{ item }}"

- name: Create the VM's
  when:
    - removing is none
    - inventory_hostname in groups['local']
  include_tasks: create_vm.yml

- name: Create local var file
  when:
    - creating is none
    - inventory_hostname == 'localhost'
  copy:
    dest: "{{ role_path }}/vars/vm_ips.yml"
    content: |
      ---
      vm_ips:
      ...

- name: Discard workers that shouldn't be removed
  when:
    - creating is none
    - inventory_hostname in groups['worker']
  include_tasks: discard_non_removing_vm.yml

- name: Get the VM IP's from worker nodes
  when:
    - creating is none
    - inventory_hostname in groups['worker']
  include_tasks: get_vm_ip.yml

- name: Stop and remove VM's from ULL IaaS
  when:
    - creating is none
    - inventory_hostname == 'localhost'
  include_tasks: remove_vm.yml

- name: Include vm_ips vars files
  when:
    - creating is none
    - inventory_hostname in groups['dhcp']
  include_vars:
    file: "{{ role_path }}/vars/vm_ips.yml"

- name: Release the VM IP's from the DHCP-DNS server
  when:
    - creating is none
    - inventory_hostname in groups['dhcp']
  include_tasks: release_dhcp_dns.yml

- name: Logout from ULL IaaS
  when: inventory_hostname in groups['local']
  include_tasks: logout.yml

...
