---
# Deploy the VM either in management or workers subnet, to be a master or a worker node.
# The Router, the DHCP-DNS and the Master server VM's must exists prior to launch this playbook.
# Target hosts: local, workers, dhcp

- name: Login into ULL IaaS
  delegate_to: local
  include_tasks: login.yml

- name: Create the VM's
  when: removing is none
  delegate_to: local
  include_tasks: create_vm.yml
  include_vars: nodes.yml

- name: Save the VM IP's and remove the VM's
  when: nodes is none
  include_vars:
    - removing.yml
    - vm_ips.yml

  block:
  - name: Get the VM network facts
    delegate_to: workers
    setup:
      gather_subset: network

  - name: Get the VM IP from workers network
    delegate_to: local
    include_tasks: get_vm_ip.yml

  - name: Stop and remove VM's from ULL IaaS
    include_tasks: remove_vm.yml
    delegate_to: local

- name: Release the VM IP's from the DHCP-DNS server
  when: nodes is none
  delegate_to: dhcp
  become: true
  include_tasks: release_dhcp_dns.yml
  include_vars:
    - removing.yml
    - vm_ips.yml

  notify: restart_services

- name: Remove erased VM IPs from variables file
  when: nodes is none
  delegate_to: local
  replace:
    path: /home/ansible/roles/ulliaas/vars/vm_ips.yml
    after: 'vm_ips:'
    regexp: '(^\s*$)'
    replace: ''

- name: Logout from ULL IaaS
  delegate_to: local
  include_tasks: logout.yml

...
