---
# Release the VM IP's from the DHCP-DNS server
# Target hosts: dhcp

- name: Clean the IP entry in the DHCP
  become: true
  replace:
    path: /var/lib/dhcpd/dhcpd.leases
    regexp: '(lease {{ vm_ips }} {[\s\S]*)}'
    replace: ''

- name: Remove the worker IP from workers.local.db
  become: true
  replace:
    path: /var/named/workers.local.db
    regexp: '(.*){{ vm_ips }}\n[^\n]+'
    replace: ''

- name: Remove empty lines from workers.local.db
  become: true
  lineinfile:
    path: /var/named/workers.local.db
    regexp: '^$'
    state: absent

- name: Remove the worker hostname from workers.local.rev
  become: true
  lineinfile:
    path: /var/named/workers.local.rev
    regexp: '(.*){{ item.node_sufix }}\.workers\.local\.'
    state: absent
  with_items: "{{ removing }}"

- name: Remove DNS jnl files
  become: true
  file:
    path: /var/named/workers.local.*.jnl
    state: absent
  notify: restart_services

...
