---
# Set the VM IP's into the vars file
# Target host: local

- name: Save the VM IP into the role variables file
  lineinfile:
    path: /home/ansible/roles/ulliaas/vars/vm_ips.yml
    line: "{{ item }}"
    insertafter: '^vm_ips:'
  loop: "{{ ip }}"

#- name: Remove "False" value from variables file
#  lineinfile:
#    path: /home/ansible/roles/ulliaas/vars/vm_ips.yml
#    regexp: '^False'
#    state: absent

- name: Convert IP lines into list items
  replace:
    path: /home/ansible/roles/ulliaas/vars/vm_ips.yml
    regexp: '^192(.+)$'
    replace: '  - 192\1'

...
